<h1>No olvidar cambiar la fecha de lectura del csv mas reciente</h1>

In [1]:
import pandas as pd

In [2]:
def createIndex(x):
    key = str(x['Date(UTC)'].year),str(x['Date(UTC)'].strftime("%H:%M:%S")),str(x['Date(UTC)'].day),x['Fee Coin'],str(x['Amount'])
    return key

In [3]:
#Amount = cantidad crypto que obtuve
#total = dinero invertido
#Sell_Porcent = porcent of position selled
#price = precio al que compre
#rest valua es el amount de crypto que queda luego de haber vendido un determinado porcentaje de esa posicion 

#df DEBE SER EL OUTPUT 
#df = pd.read_csv("../BinanceDataSet/Exportar historial de operaciones-2022-06-07.csv")
df = pd.read_csv("../Output/CLEAN_data_11-09-2023_p2.csv")
df['Date(UTC)'] = pd.to_datetime(df['Date(UTC)']) 
df['key'] = df.apply(createIndex,axis=1)
df['rest_value'] = df['Amount'] - df['Amount'] * (df['sell_Porcent']/100) 


# #EL RDF DEBE SER DESDE LA FECHA DEL ULTIMO REPORTE HASTA EL DIA anterior 

rdf = pd.read_csv("../BinanceDataSet/Export Trade History-2023-11-14 18_02_39.csv")

rdf['Date(UTC)'] = pd.to_datetime(rdf['Date(UTC)'])
rdf['sell_Porcent'] = 0
rdf['is_Open'] = True
rdf['key'] = rdf.apply(createIndex,axis=1)
rdf['rest_value'] = rdf['Amount'] - rdf['Amount'] * (rdf['sell_Porcent']/100) 
df.head()

,Date(UTC),Market,Type,Price,Amount,Total,Fee,Fee Coin,sell_Porcent,is_Open,key,rest_value,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,2022-05-16 02:42:00,LUNABUSD,BUY,0.00026,38389.18,9.999997,38.38918,LUNA,0,True,"(2022, 02:42:00, 16, LUNA, 38389.18)",38389.18,NaN,NaN,NaN
1,2022-06-13 01:34:00,VETBUSD,BUY,0.02487,410.10,10.199187,0.41010,VET,0,True,"(2022, 01:34:00, 13, VET, 410.1)",410.10,NaN,NaN,NaN
2,2022-07-12 01:56:00,ROSEUSDT,BUY,0.04687,215.40,10.095798,0.21540,ROSE,0,True,"(2022, 01:56:00, 12, ROSE, 215.4)",215.40,NaN,NaN,NaN
3,2022-06-12 02:47:00,ROSEUSDT,BUY,0.05515,185.20,10.213780,0.18520,ROSE,0,True,"(2022, 02:47:00, 12, ROSE, 185.2)",185.20,NaN,NaN,NaN
4,2023-03-03 02:41:00,ROSEUSDT,BUY,0.05725,234.40,13.419400,0.23440,ROSE,20,True,"(2023, 02:41:00, 3, ROSE, 234.4)",187.52,NaN,NaN,NaN

In [4]:
# dotDf = df.loc[(df['Market']=='DOTUSDT') | (df['Market']=='DOTBUSD')]
# dotDf[dotDf['Price']>4.90]
# dotDf.drop_duplicates(subset=['key','Price'],keep='first',inplace=True)
# dotDf[dotDf['Price']>4.90]

In [5]:
rdf.head()

,Date(UTC),Market,Type,Price,Amount,Total,Fee,Fee Coin,sell_Porcent,is_Open,key,rest_value
0,2023-11-14 15:33:18,BTCUSDT,BUY,36000.00000,0.00016,5.760000,1.600000e-07,BTC,0,True,"(2023, 15:33:18, 14, BTC, 0.00016)",0.00016
1,2023-11-14 00:10:58,DOTUSDT,BUY,5.25000,0.97000,5.092500,9.700000e-04,DOT,0,True,"(2023, 00:10:58, 14, DOT, 0.97)",0.97000
2,2023-11-14 00:07:23,ADAUSDT,BUY,0.35400,14.40000,5.097600,1.440000e-02,ADA,0,True,"(2023, 00:07:23, 14, ADA, 14.4)",14.40000
3,2023-11-14 00:06:30,DOTUSDT,BUY,5.33000,1.12000,5.969600,1.120000e-03,DOT,0,True,"(2023, 00:06:30, 14, DOT, 1.12)",1.12000
4,2023-11-14 00:01:48,ROSEUSDT,BUY,0.06867,72.80000,4.999176,7.280000e-02,ROSE,0,True,"(2023, 00:01:48, 14, ROSE, 72.8)",72.80000

In [6]:
df = pd.concat([df,rdf])
df = df.reset_index(drop=True)
df.drop_duplicates(subset=['key','Price'],keep='first',inplace=True)
df = df.loc[df['is_Open']==True]
df

,Date(UTC),Market,Type,Price,Amount,Total,Fee,Fee Coin,sell_Porcent,is_Open,key,rest_value,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,2022-05-16 02:42:00,LUNABUSD,BUY,0.00026,38389.18,9.999997,38.389180,LUNA,0,True,"(2022, 02:42:00, 16, LUNA, 38389.18)",38389.18,NaN,NaN,NaN
1,2022-06-13 01:34:00,VETBUSD,BUY,0.02487,410.10,10.199187,0.410100,VET,0,True,"(2022, 01:34:00, 13, VET, 410.1)",410.10,NaN,NaN,NaN
2,2022-07-12 01:56:00,ROSEUSDT,BUY,0.04687,215.40,10.095798,0.215400,ROSE,0,True,"(2022, 01:56:00, 12, ROSE, 215.4)",215.40,NaN,NaN,NaN
3,2022-06-12 02:47:00,ROSEUSDT,BUY,0.05515,185.20,10.213780,0.185200,ROSE,0,True,"(2022, 02:47:00, 12, ROSE, 185.2)",185.20,NaN,NaN,NaN
4,2023-03-03 02:41:00,ROSEUSDT,BUY,0.05725,234.40,13.419400,0.234400,ROSE,20,True,"(2023, 02:41:00, 3, ROSE, 234.4)",187.52,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,2023-11-12 22:55:52,ADAUSDT,SELL,0.38530,58.00,22.347400,0.022347,USDT,0,True,"(2023, 22:55:52, 12, USDT, 58.0)",58.00,NaN,NaN,NaN
441,2023-11-12 22:51:28,DOTUSDT,BUY,5.72000,0.88,5.033600,0.000880,DOT,0,True,"(2023, 22:51:28, 12, DOT, 0.88)",0.88,NaN,NaN,NaN
442,2023-11-12 22:49:10,LINKUSDT,BUY,16.09600,0.31,4.989760,0.000310,LINK,0,True,"(2023, 22:49:10, 12, LINK, 0.31)",0.31,NaN,NaN,NaN
443,2023-11-12 22:28:03,DOTUSDT,SELL,5.73700,4.68,26.849160,0.026849,USDT,0,True,"(2023, 22:28:03, 12, USDT, 4.68)",4.68,NaN,NaN,NaN
444,2023-11-12 22:28:03,DOTUSDT,SELL,5.73700,3.90,22.374300,0.022374,USDT,0,True,"(2023, 22:28:03, 12, USDT, 3.9)",3.90,NaN,NaN,NaN

In [7]:
df.head()

,Date(UTC),Market,Type,Price,Amount,Total,Fee,Fee Coin,sell_Porcent,is_Open,key,rest_value,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,2022-05-16 02:42:00,LUNABUSD,BUY,0.00026,38389.18,9.999997,38.38918,LUNA,0,True,"(2022, 02:42:00, 16, LUNA, 38389.18)",38389.18,NaN,NaN,NaN
1,2022-06-13 01:34:00,VETBUSD,BUY,0.02487,410.10,10.199187,0.41010,VET,0,True,"(2022, 01:34:00, 13, VET, 410.1)",410.10,NaN,NaN,NaN
2,2022-07-12 01:56:00,ROSEUSDT,BUY,0.04687,215.40,10.095798,0.21540,ROSE,0,True,"(2022, 01:56:00, 12, ROSE, 215.4)",215.40,NaN,NaN,NaN
3,2022-06-12 02:47:00,ROSEUSDT,BUY,0.05515,185.20,10.213780,0.18520,ROSE,0,True,"(2022, 02:47:00, 12, ROSE, 185.2)",185.20,NaN,NaN,NaN
4,2023-03-03 02:41:00,ROSEUSDT,BUY,0.05725,234.40,13.419400,0.23440,ROSE,20,True,"(2023, 02:41:00, 3, ROSE, 234.4)",187.52,NaN,NaN,NaN

In [8]:
# dfg = df.groupby('Fee Coin').sum()
# dfg
#df['Fee Coin'] == 'BNB'

In [9]:
adaDf = df.loc[(df['Market']=='ADAUSDT') | (df['Market']=='ADABUSD')]
btcDf = df.loc[(df['Market']=='BTCUSDT') | (df['Market']=='BTCBUSD')]
ethDf = df.loc[(df['Market']=='ETHUSDT') | (df['Market']=='ETHBUSD')]
dotDf = df.loc[(df['Market']=='DOTUSDT') | (df['Market']=='DOTBUSD')]
solDf = df.loc[(df['Market']=='SOLUSDT') | (df['Market']=='SOLBUSD')]
roseDf = df.loc[(df['Market']=='ROSEUSDT') | (df['Market']=='ROSEBUSD')]
bnbDf = df.loc[(df['Market']=='BNBUSDT') | (df['Market']=='BNBBUSD')]



adaDf.head()

,Date(UTC),Market,Type,Price,Amount,Total,Fee,Fee Coin,sell_Porcent,is_Open,key,rest_value,Unnamed: 12,Unnamed: 13,Unnamed: 14
12,2023-10-11 16:39:00,ADAUSDT,BUY,0.2470,20.2,4.98940,0.0202,ADA,0,True,"(2023, 16:39:00, 11, ADA, 20.2)",20.20,NaN,NaN,NaN
13,2023-08-31 16:20:00,ADAUSDT,BUY,0.2586,38.6,9.98196,0.0386,ADA,0,True,"(2023, 16:20:00, 31, ADA, 38.6)",38.60,NaN,NaN,NaN
14,2022-12-16 23:56:00,ADABUSD,BUY,0.2638,40.4,10.65752,0.0404,ADA,60,True,"(2022, 23:56:00, 16, ADA, 40.4)",16.16,NaN,NaN,NaN
15,2023-10-25 20:50:00,ADAUSDT,BUY,0.2795,17.8,4.97510,0.0178,ADA,0,True,"(2023, 20:50:00, 25, ADA, 17.8)",17.80,NaN,NaN,NaN
16,2022-12-16 22:34:00,ADAUSDT,BUY,0.2800,36.0,10.08000,0.0360,ADA,70,True,"(2022, 22:34:00, 16, ADA, 36.0)",10.80,NaN,NaN,NaN

In [10]:
dotDf[dotDf['Price']>4.90]

,Date(UTC),Market,Type,Price,Amount,Total,Fee,Fee Coin,sell_Porcent,is_Open,key,rest_value,Unnamed: 12,Unnamed: 13,Unnamed: 14
114,2023-11-07 22:46:00,DOTUSDT,BUY,4.917,1.01,4.96617,0.001010,DOT,30,True,"(2023, 22:46:00, 7, DOT, 1.01)",0.707,NaN,NaN,NaN
115,2023-11-09 16:12:00,DOTUSDT,BUY,4.920,1.03,5.06760,0.001030,DOT,0,True,"(2023, 16:12:00, 9, DOT, 1.03)",1.030,NaN,NaN,NaN
116,2023-11-09 16:12:00,DOTUSDT,BUY,4.930,1.03,5.07790,0.001030,DOT,0,True,"(2023, 16:12:00, 9, DOT, 1.03)",1.030,NaN,NaN,NaN
117,2023-11-09 16:12:00,DOTUSDT,BUY,4.950,1.03,5.09850,0.001030,DOT,10,True,"(2023, 16:12:00, 9, DOT, 1.03)",0.927,NaN,NaN,NaN
118,2023-11-09 16:11:00,DOTUSDT,BUY,4.980,1.02,5.07960,0.001020,DOT,10,True,"(2023, 16:11:00, 9, DOT, 1.02)",0.918,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,2023-11-13 04:30:49,DOTUSDT,BUY,5.659,0.88,4.97992,0.000880,DOT,0,True,"(2023, 04:30:49, 13, DOT, 0.88)",0.880,NaN,NaN,NaN
438,2023-11-12 23:20:08,DOTUSDT,BUY,5.680,0.89,5.05520,0.000890,DOT,0,True,"(2023, 23:20:08, 12, DOT, 0.89)",0.890,NaN,NaN,NaN
441,2023-11-12 22:51:28,DOTUSDT,BUY,5.720,0.88,5.03360,0.000880,DOT,0,True,"(2023, 22:51:28, 12, DOT, 0.88)",0.880,NaN,NaN,NaN
443,2023-11-12 22:28:03,DOTUSDT,SELL,5.737,4.68,26.84916,0.026849,USDT,0,True,"(2023, 22:28:03, 12, USDT, 4.68)",4.680,NaN,NaN,NaN
444,2023-11-12 22:28:03,DOTUSDT,SELL,5.737,3.90,22.37430,0.022374,USDT,0,True,"(2023, 22:28:03, 12, USDT, 3.9)",3.900,NaN,NaN,NaN

In [11]:
adaDf = adaDf.loc[adaDf['Type']== 'BUY']
btcDf = btcDf.loc[btcDf['Type']== 'BUY']
ethDf = ethDf.loc[ethDf['Type']== 'BUY']
dotDf = dotDf.loc[dotDf['Type']== 'BUY']
solDf = solDf.loc[solDf['Type']== 'BUY']
roseDf = roseDf.loc[roseDf['Type']== 'BUY']
bnbDf = bnbDf.loc[bnbDf['Type']== 'BUY']
df = df.loc[df['Type']== 'BUY']

In [12]:
(df['Type']=='SELL').sum()

0

In [13]:
#Order de mayor a menor 
adaDf = adaDf.sort_values(by='Price')
ethDf = ethDf.sort_values(by='Price')
btcDf = btcDf.sort_values(by='Price')
dotDf = dotDf.sort_values(by='Price')
solDf = solDf.sort_values(by='Price')
roseDf = roseDf.sort_values(by='Price')
bnbDf = bnbDf.sort_values(by='Price')

In [14]:
#New Index
btcDf = btcDf.reset_index(drop=True)
dotDf = dotDf.reset_index(drop=True)
adaDf = adaDf.reset_index(drop=True)
ethDf = ethDf.reset_index(drop=True)
solDf = solDf.reset_index(drop=True)
roseDf = roseDf.reset_index(drop=True)
bnbDf = bnbDf.reset_index(drop=True)

btcDf

,Date(UTC),Market,Type,Price,Amount,Total,Fee,Fee Coin,sell_Porcent,is_Open,key,rest_value,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,2022-11-09 22:06:00,BTCUSDT,BUY,15650.00,0.00064,10.016000,0.000000e+00,BNB,90,True,"(2022, 22:06:00, 9, BNB, 0.00064)",0.000064,NaN,NaN,NaN
1,2022-12-16 23:11:00,BTCBUSD,BUY,16600.00,0.00061,10.126000,0.000000e+00,BNB,90,True,"(2022, 23:11:00, 16, BNB, 0.00061)",0.000061,NaN,NaN,NaN
2,2022-11-02 22:53:00,BTCUSDT,BUY,20060.00,0.00050,10.030000,0.000000e+00,BNB,50,True,"(2022, 22:53:00, 2, BNB, 0.0005)",0.000250,NaN,NaN,NaN
3,2023-03-10 13:52:00,BTCUSDT,BUY,20215.73,0.00059,11.927281,0.000000e+00,BNB,60,True,"(2023, 13:52:00, 10, BNB, 0.00059)",0.000236,NaN,NaN,NaN
4,2023-02-09 20:19:00,BTCBUSD,BUY,21870.00,0.00046,10.060200,0.000000e+00,BNB,60,True,"(2023, 20:19:00, 9, BNB, 0.00046)",0.000184,NaN,NaN,NaN
5,2022-08-19 06:42:00,BTCUSDT,BUY,21920.00,0.00046,10.083200,0.000000e+00,BNB,70,True,"(2022, 06:42:00, 19, BNB, 0.00046)",0.000138,NaN,NaN,NaN
6,2023-03-03 01:57:00,BTCUSDT,BUY,22064.00,0.00045,9.928800,0.000000e+00,BNB,80,True,"(2023, 01:57:00, 3, BNB, 0.00045)",0.000090,NaN,NaN,NaN
7,2023-03-03 21:20:00,BTCUSDT,BUY,22150.00,0.00046,10.189000,0.000000e+00,BNB,80,True,"(2023, 21:20:00, 3, BNB, 0.00046)",0.000092,NaN,NaN,NaN
8,2023-01-30 21:45:00,BTCBUSD,BUY,22725.00,0.00045,10.226250,0.000000e+00,BNB,90,True,"(2023, 21:45:00, 30, BNB, 0.00045)",0.000045,NaN,NaN,NaN
9,2023-03-15 16:11:00,BTCBUSD,BUY,24236.00,0.00042,10.179120,0.000000e+00,BNB,90,True,"(2023, 16:11:00, 15, BNB, 0.00042)",0.000042,NaN,NaN,NaN
10,2023-09-06 17:05:00,BTCUSDT,BUY,25490.00,0.00040,10.196000,4.000000e-07,BTC,20,True,"(2023, 17:05:00, 6, BTC, 0.0004)",0.000320,NaN,NaN,NaN
11,2023-06-10 17:03:00,BTCUSDT,BUY,25500.00,0.00040,10.200000,4.000000e-07,BTC,20,True,"(2023, 17:03:00, 10, BTC, 0.0004)",0.000320,NaN,NaN,NaN
12,2023-06-05 17:15:00,BTCUSDT,BUY,25685.00,0.00039,10.017150,3.900000e-07,BTC,20,True,"(2023, 17:15:00, 5, BTC, 0.00039)",0.000312,NaN,NaN,NaN
13,2023-09-07 11:42:00,BTCUSDT,BUY,25715.27,0.00038,9.771803,3.800000e-07,BTC,20,True,"(2023, 11:42:00, 7, BTC, 0.00038)",0.000304,NaN,NaN,NaN
14,2023-06-10 08:44:00,BTCUSDT,BUY,25718.79,0.00038,9.773140,3.800000e-07,BTC,30,True,"(2023, 08:44:00, 10, BTC, 0.00038)",0.000266,NaN,NaN,NaN
15,2023-06-05 17:14:00,BTCUSDT,BUY,25718.86,0.00038,9.773167,3.800000e-07,BTC,30,True,"(2023, 17:14:00, 5, BTC, 0.00038)",0.000266,NaN,NaN,NaN
16,2023-06-05 17:13:00,BTCUSDT,BUY,25734.23,0.00077,19.815357,7.700000e-07,BTC,40,True,"(2023, 17:13:00, 5, BTC, 0.00077)",0.000462,NaN,NaN,NaN
17,2023-09-04 16:08:00,BTCUSDT,BUY,25849.89,0.00038,9.822958,3.800000e-07,BTC,40,True,"(2023, 16:08:00, 4, BTC, 0.00038)",0.000228,NaN,NaN,NaN
18,2023-08-31 21:07:00,BTCUSDT,BUY,25900.00,0.00039,10.101000,3.900000e-07,BTC,40,True,"(2023, 21:07:00, 31, BTC, 0.00039)",0.000234,NaN,NaN,NaN
19,2023-05-25 04:26:00,BTCUSDT,BUY,26234.70,0.00038,9.969186,3.800000e-07,BTC,50,True,"(2023, 04:26:00, 25, BTC, 0.00038)",0.000190,NaN,NaN,NaN
20,2023-05-24 19:08:00,BTCUSDT,BUY,26242.59,0.00041,10.759462,4.100000e-07,BTC,50,True,"(2023, 19:08:00, 24, BTC, 0.00041)",0.000205,NaN,NaN,NaN
21,2023-09-25 01:43:00,BTCUSDT,BUY,26258.80,0.00041,10.766108,4.100000e-07,BTC,0,True,"(2023, 01:43:00, 25, BTC, 0.00041)",0.000410,NaN,NaN,NaN
22,2023-05-24 21:45:00,BTCUSDT,BUY,26364.00,0.00038,10.018320,3.800000e-07,BTC,50,True,"(2023, 21:45:00, 24, BTC, 0.00038)",0.000190,NaN,NaN,NaN
23,2023-09-15 11:59:00,BTCUSDT,BUY,26400.00,0.00038,10.032000,3.800000e-07,BTC,0,True,"(2023, 11:59:00, 15, BTC, 0.00038)",0.000380,NaN,NaN,NaN
24,2023-06-07 19:04:00,BTCUSDT,BUY,26459.15,0.00006,1.587549,6.000000e-08,BTC,80,True,"(2023, 19:04:00, 7, BTC, 6e-05)",0.000012,NaN,NaN,NaN
25,2023-06-07 19:04:00,BTCUSDT,BUY,26459.15,0.00031,8.202336,3.100000e-07,BTC,80,True,"(2023, 19:04:00, 7, BTC, 0.00031)",0.000062,NaN,NaN,NaN
26,2023-08-31 16:37:00,BTCUSDT,BUY,26500.00,0.00038,10.070000,3.800000e-07,BTC,80,True,"(2023, 16:37:00, 31, BTC, 0.00038)",0.000076,NaN,NaN,NaN
27,2023-08-31 16:31:00,BTCUSDT,BUY,26541.90,0.00038,10.085922,3.800000e-07,BTC,90,True,"(2023, 16:31:00, 31, BTC, 0.00038)",0.000038,NaN,NaN,NaN
28,2023-06-05 15:24:00,BTCUSDT,BUY,26550.00,0.00043,11.416500,4.300000e-07,BTC,90,True,"(2023, 15:24:00, 5, BTC, 0.00043)",0.000043,NaN,NaN,NaN
29,2023-10-12 16:26:00,BTCUSDT,BUY,26580.00,0.00019,5.050200,1.900000e-07,BTC,0,True,"(2023, 16:26:00, 12, BTC, 0.00019)",0.000190,NaN,NaN,NaN
30,2023-09-21 12:35:00,BTCUSDT,BUY,26600.00,0.00038,10.108000,3.800000e-07,BTC,0,True,"(2023, 12:35:00, 21, BTC, 0.00038)",0.000380,NaN,NaN,NaN
31,2023-10-11 17:45:00,BTCUSDT,BUY,26610.00,0.00022,5.854200,2.200000e-07,BTC,0,True,"(2023, 17:45:00, 11, BTC, 0.00022)",0.000220,NaN,NaN,NaN
32,2023-10-11 17:16:00,BTCUSDT,BUY,26630.00,0.00019,5.059700,1.900000e-07,BTC,0,True,"(2023, 17:16:00, 11, BTC, 0.00019)",0.000190,NaN,NaN,NaN
33,2023-08-31 16:30:00,BTCUSDT,BUY,26644.40,0.00037,9.858428,3.700000e-07,BTC,0,True,"(2023, 16:30:00, 31, BTC, 0.00037)",0.000370,NaN,NaN,NaN
34,2023-05-27 17:24:00,BTCUSDT,BUY,26668.34,0.00037,9.867286,3.700000e-07,BTC,10,True,"(2023, 17:24:00, 27, BTC, 0.00037)",0.000333,NaN,NaN,NaN
35,2023-10-11 16:43:00,BTCUSDT,BUY,26688.00,0.00022,5.871360,2.200000e-07,BTC,0,True,"(2023, 16:43:00, 11, BTC, 0.00022)",0.000220,NaN,NaN,NaN
36,2023-10-11 16:36:00,BTCUSDT,BUY,26715.01,0.00022,5.877302,2.200000e-07,BTC,0,True,"(2023, 16:36:00, 11, BTC, 0.00022)",0.000220,NaN,NaN,NaN
37,2023-08-31 16:26:00,BTCUSDT,BUY,26730.00,0.00038,10.157400,3.800000e-07,BTC,20,True,"(2023, 16:26:00, 31, BTC, 0.00038)",0.000304,NaN,NaN,NaN
38,2023-10-11 20:15:00,BTCUSDT,BUY,26735.65,0.00018,4.812417,1.800000e-07,BTC,10,True,"(2023, 20:15:00, 11, BTC, 0.00018)",0.000162,NaN,NaN,NaN
39,2023-06-07 12:17:00,BTCUSDT,BUY,26760.00,0.00038,10.168800,3.800000e-07,BTC,20,True,"(2023, 12:17:00, 7, BTC, 0.00038)",0.000304,NaN,NaN,NaN
40,2023-06-01 23:30:00,BTCUSDT,BUY,26760.00,0.00038,10.168800,3.800000e-07,BTC,30,True,"(2023, 23:30:00, 1, BTC, 0.00038)",0.000266,NaN,NaN,NaN
41,2023-06-01 06:03:00,BTCUSDT,BUY,26850.34,0.00037,9.934626,3.700000e-07,BTC,50,True,"(2023, 06:03:00, 1, BTC, 0.00037)",0.000185,NaN,NaN,NaN
42,2023-10-14 02:50:00,BTCUSDT,BUY,26909.99,0.00018,4.843798,1.800000e-07,BTC,30,True,"(2023, 02:50:00, 14, BTC, 0.00018)",0.000126,NaN,NaN,NaN
43,2023-05-31 14:20:00,BTCUSDT,BUY,26936.35,0.00037,9.966449,3.700000e-07,BTC,70,True,"(2023, 14:20:00, 31, BTC, 0.00037)",0.000111,NaN,NaN,NaN
44,2023-05-31 05:07:00,BTCUSDT,BUY,27206.41,0.00036,9.794308,3.600000e-07,BTC,90,True,"(2023, 05:07:00, 31, BTC, 0.00036)",0.000036,NaN,NaN,NaN
45,2023-10-16 13:59:00,BTCUSDT,BUY,27994.85,0.00018,5.039073,1.800000e-07,BTC,70,True,"(2023, 13:59:00, 16, BTC, 0.00018)",0.000054,NaN,NaN,NaN
46,2023-10-22 07:40:00,BTCUSDT,BUY,29840.00,0.00017,5.072800,1.700000e-07,BTC,20,True,"(2023, 07:40:00, 22, BTC, 0.00017)",0.000136,NaN,NaN,NaN
47,2023-10-23 04:09:00,BTCUSDT,BUY,30655.92,0.00017,5.211506,1.700000e-07,BTC,70,True,"(2023, 04:09:00, 23, BTC, 0.00017)",0.000051,NaN,NaN,NaN
48,2023-10-27 17:07:00,BTCUSDT,BUY,33400.00,0.00015,5.010000,1.500000e-07,BTC,20,True,"(2023, 17:07:00, 27, BTC, 0.00015)",0.000120,NaN,NaN,NaN
49,2023-10-24 05:56:00,BTCUSDT,BUY,34000.00,0.00015,5.100000,1.500000e-07,BTC,100,True,"(2023, 05:56:00, 24, BTC, 0.00015)",0.000000,NaN,NaN,NaN
50,2023-11-01 14:49:00,BTCUSDT,BUY,34280.33,0.00015,5.142049,1.500000e-07,BTC,30,True,"(2023, 14:49:00, 1, BTC, 0.00015)",0.000105,NaN,NaN,NaN
51,2023-10-30 02:00:00,BTCUSDT,BUY,34300.00,0.00015,5.145000,1.500000e-07,BTC,40,True,"(2023, 02:00:00, 30, BTC, 0.00015)",0.000090,NaN,NaN,NaN
52,2023-11-03 04:46:00,BTCUSDT,BUY,34430.00,0.00015,5.164500,1.500000e-07,BTC,10,True,"(2023, 04:46:00, 3, BTC, 0.00015)",0.000135,NaN,NaN,NaN
53,2023-10-29 21:58:00,BTCUSDT,BUY,34500.00,0.00015,5.175000,1.500000e-07,BTC,60,True,"(2023, 21:58:00, 29, BTC, 0.00015)",0.000060,NaN,NaN,NaN
54,2023-11-07 10:48:00,BTCUSDT,BUY,34600.00,0.00015,5.190000,1.500000e-07,BTC,20,True,"(2023, 10:48:00, 7, BTC, 0.00015)",0.000120,NaN,NaN,NaN
55,2023-11-02 13:44:00,BTCUSDT,BUY,34754.00,0.00015,5.213100,1.500000e-07,BTC,20,True,"(2023, 13:44:00, 2, BTC, 0.00015)",0.000120,NaN,NaN,NaN
56,2023-10-25 15:42:00,BTCUSDT,BUY,34756.72,0.00014,4.865941,1.400000e-07,BTC,90,True,"(2023, 15:42:00, 25, BTC, 0.00014)",0.000014,NaN,NaN,NaN
57,2023-11-06 01:42:00,BTCUSDT,BUY,34890.00,0.00015,5.233500,1.500000e-07,BTC,60,True,"(2023, 01:42:00, 6, BTC, 0.00015)",0.000060,NaN,NaN,0.001045
58,2023-11-14 15:33:18,BTCUSDT,BUY,36000.00,0.00016,5.760000,1.600000e-07,BTC,0,True,"(2023, 15:33:18, 14, BTC, 0.00016)",0.000160,NaN,NaN,NaN
59,2023-11-13 21:14:29,BTCUSDT,BUY,36400.00,0.00016,5.824000,1.600000e-07,BTC,0,True,"(2023, 21:14:29, 13, BTC, 0.00016)",0.000160,NaN,NaN,NaN

In [15]:
df.to_csv('../Output/CLEAN_data_11-14-2023.csv',index=False)
df.to_csv('../Output/BackUpMainFiles/CLEAN_data_11-14-2023.csv',index=False)
# adaDf.to_csv('../Output/ADA_clean_data_12-20-2022.csv')
# btcDf.to_csv('../Output/BTC_clean_data_12-20-2022.csv')
# ethDf.to_csv('../Output/ETH_clean_data_12-20-2022.csv')
# dotDf.to_csv('../Output/Dot_clean_data_12-20-2022.csv')
# solDf.to_csv('../Output/Sol_clean_data_12-20-2022.csv')
# roseDf.to_csv('../Output/Rose_clean_data_12-20-2022.csv')
# bnbDf.to_csv('../Output/BNB_clean_data_12-20-2022.csv')